CREATE TABLE public.deal (
                             id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                             deal_amount numeric(38, 2) NULL,
                             deal_timestamp timestamp(6) NOT NULL,
                             checksum varchar(255) NULL,
                             from_currency_iso_code varchar(255) NULL,
                             to_currency_iso_code varchar(255) NULL,
                             CONSTRAINT deal_pkey PRIMARY KEY (id),
                             CONSTRAINT unique_checksum UNIQUE (checksum)
);